# Generated by Django 4.2.9 on 2024-02-06 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("north_kingstown", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Drinks",
            new_name="Drink",
        ),
    ]
